### ISSUE TITLE
Rails 5 beta3 throwing NameError: uninitialized constant ActiveRecord::XmlSerializer

### ISSUE THREAD

**Issue by dbaker24** [rails/activemodel-serializers-xml#10]
Trying to add this to a Rails 5 beta 3 project. Install is fine gem 'activemodel-serializers-xml' but when used in any model it throws the NameError: uninitialized constant ActiveRecord::XmlSerializer.

class User < ApplicationRecord
  include ActiveRecord::XmlSerializer 
end

**Comment by rafaelfranca** [comment]
Which version of this gem are you using?

**Comment by dbaker24** [comment]
I'm sorry @rafaelfranca... it is activemodel-serializers-xml (1.0.0). Thank you for the response...

**Comment by rafaelfranca** [comment]
Could you try the master branch?

**Comment by dbaker24** [comment]
This is what I have in my Gemfile...

gem 'activemodel-serializers-xml', :git => 'https://github.com/rails/activemodel-serializers-xml.git', :branch => 'master'

**Comment by rafaelfranca** [comment]
Could you try with?

```
gem 'activemodel-serializers-xml', :git => 'https://github.com/rails/activemodel-serializers-xml.git', :sha => 'f380ea5ddefcb9a37f4fbc47606ed6fbecdb2b2a'
```

**Comment by dbaker24** [comment]
Just gave it a shot...

[!] There was an error parsing `Gemfile`: You passed :sha as an option for gem 'activemodel-serializers-xml', but it is invalid. Valid options are: group, groups, git, path, glob, name, branch, ref, tag, require, submodules, platform, platforms, type, source, install_if, github, gist, bitbucket. Bundler cannot continue.

bundler (1.11.2)

**Comment by rafaelfranca** [comment]
Use `ref` instead of `sha`

**Comment by dbaker24** [comment]
That did indeed work for the Gemfile.  Thank you.

I am now receiving this error...

TypeError: wrong argument type Class (expected Module)

Model...
class User < ApplicationRecord
  include ActiveRecord::XmlSerializer
  has_one :userprofile, :autosave => true  
end

**Comment by rafaelfranca** [comment]
Oh. You don't need to include anything. This gem works out of box with Active Record. This error is because you are trying to include a class (`ActiveRecord::XmlSerializer` is a class) and `include` only accept modules.

**Comment by dbaker24** [comment]
@rafaelfranca.... thank you very, very much. It is now working as expected.

Do you know when the "normal" gem 'activemodel-serializers-xml' entry in the Gemfile will work as expected?

**Comment by rafaelfranca** [comment]
As soon I release a new version. I'll try to do it today and I'll let you know.

**Comment by rafaelfranca** [comment]
1.0.1 was released.
