### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by zzak** [rails/activemodel-serializers-xml#5]

**Comment by greysteil** [comment]
Now that Rails 5.0.0.beta1 is out it would be great to get a release of this.

**Comment by greysteil** [comment]
@rafaelfranca - is there a proposed date for pushing this to Rubygems?

**Comment by zzak** [comment]
@rafaelfranca Thank you for getting to this! <3 <3

**Comment by greysteil** [comment]
:heart:
